/*
 * TokenSuite.java
 * JUnit based test
 *
 * Created on March 13, 2007, 11:29 PM
 */

package edu.tuke.beast.token;

import junit.framework.*;

/**
 *
 * @author blur
 */
public class TokenSuite extends TestCase {
    
    public TokenSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("TokenSuite");
        suite.addTest(edu.tuke.beast.token.ExcitedIndexTest.suite());
        suite.addTest(edu.tuke.beast.token.ExcitedIndexStrengthComparatorTest.suite());
        suite.addTest(edu.tuke.beast.token.ExcitedTokenTest.suite());
        suite.addTest(edu.tuke.beast.token.ExcitedTokenStrengthComparatorTest.suite());
        suite.addTest(edu.tuke.beast.token.TokenTest.suite());
        return suite;
    }
    
}
