/*
 * FascicleSuite.java
 * JUnit based test
 *
 * Created on March 13, 2007, 11:29 PM
 */

package edu.tuke.beast.fascicle;

import junit.framework.*;

/**
 *
 * @author blur
 */
public class FascicleSuite extends TestCase {
    
    public FascicleSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("FascicleSuite");
        suite.addTest(edu.tuke.beast.fascicle.FascicleTest.suite());
        return suite;
    }
    
}
