/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnalyzePanel.java
 *
 * Created on Dec 7, 2008, 3:31:31 AM
 */
package edu.tuke.beast.panel;

import edu.tuke.beast.Beast;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.visu.canvas.WordcircleCanvas;
import edu.tuke.beast.token.ExcitedIndex;
import edu.tuke.beast.token.Token;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author blur
 */
public class AnalyzePanel extends BeastPanel {

    private static final long serialVersionUID = 8572072136186584321L;
    final WordcircleCanvas sPanel = new WordcircleCanvas();
    
    

    /** Creates new form AnalyzePanel */
    public AnalyzePanel() {
        initComponents();
    }

    public AnalyzePanel(Beast beast) {
        super(beast);
        initComponents();
        
        this.add(sPanel, BorderLayout.CENTER);

        setName("Analyze");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextField.setText("text to analyze...");
        jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField, java.awt.BorderLayout.CENTER);

        jButton.setText("OK");
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jButton, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendText();
        }
    }//GEN-LAST:event_jTextFieldKeyPressed

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
        
        sendText();
    }//GEN-LAST:event_jButtonMouseClicked

    private void sendText() {
        String input = jTextField.getText();
        String text[] = input.split(" ");

        List<ExcitedIndex<String>> words = new ArrayList<ExcitedIndex<String>>();
        double sig_m[][] = new double[text.length][text.length];
        double wei_m[][] = new double[text.length][text.length];

        for (String word : text) {
            int occ = beast.getLexicon().getOccurences(new Token<String>(word));
            logger.debug(word + ':' + occ);
            words.add(new ExcitedIndex<String>(word, occ));
        }

        for (int i = 0; i < text.length - 1; i++) {
            for (int j = i + 1; j < text.length; j++) {
                int a = beast.getLexicon().getIndex(new Token<String>(text[i]));
                int b = beast.getLexicon().getIndex(new Token<String>(text[j]));
                if (j - i - 1 < beast.getRegion().fascicle.length) {
                    double sig = beast.getRegion().getFascicle(j - i - 1).getSignificance(a, b);

                    logger.debug(a+" S "+b+" = "+sig);

                    double wei = beast.getRegion().getFascicle(j - i - 1).getWeigth(a, b);
                    double wei2 = beast.getRegion().getFascicle(j - i - 1).getWeigthInv(a, b);
                    logger.debug(text[i] + "->" + text[j] + '=' + ((Math.floor(sig * 10000)) / 10000) + ':' + ((Math.floor(wei * 10000)) / 10000));

                    sig_m[i][j] = sig;//(Math.floor(sig * 10000000)) / 1000000;
                    wei_m[i][j] = wei;//(Math.floor(wei * 10000000)) / 1000000;
                    wei_m[j][i] = wei2;//(Math.floor(wei2 * 10000000)) / 1000000;
                }

            }
        }

        sPanel.setSentence(words, sig_m, wei_m);
    //sPanel.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables

    public static void main(String s[]) {


        Beast beast = null;
        try {
            beast = new Beast("/home/vrockai/School/Beast/CORTEX");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        try {
            JFrame f = new JFrame("ShapesDemo2D");
            f.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosing(WindowEvent e) {
                    System.exit(0);
                }
            });


            JPanel applet = new AnalyzePanel(beast);

            f.getContentPane().add("Center", applet);
            //applet.init();
            f.pack();

            f.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
