/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhrasePanel.java
 *
 * Created on Dec 8, 2008, 7:15:32 PM
 */
package edu.tuke.beast.panel;

import edu.tuke.beast.Beast;
import edu.tuke.beast.cortex.AnnotateCortex;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.beast.token.Token;

/**
 *
 * @author blur
 */
public class AnnotationPanel extends BeastPanel {

    private static final long serialVersionUID = -2113933703833778223L;
    
    public static final Token NULL_TOKEN = new Token<String>(null);
    private Token[] tokenWindow = {NULL_TOKEN, NULL_TOKEN, NULL_TOKEN, NULL_TOKEN, NULL_TOKEN};
    private AnnotateCortex annCortex;


    /** Creates new form PhrasePanel */
    public AnnotationPanel() {
        initComponents();
        jEditorPane1.setContentType("text/html;");
    }

    public AnnotationPanel(Beast b) {
        super(b);
        annCortex = new AnnotateCortex(cortex);
        initComponents();
        jEditorPane1.setContentType("text/html;");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAnalyze = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButtonAnalyze.setText("analyze");
        jButtonAnalyze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnalyzeMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAnalyze);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setLineWrap(true);
        jTextAreaInput.setRows(5);
        jTextAreaInput.setText("type your text here...");
        jScrollPane2.setViewportView(jTextAreaInput);

        jSplitPane1.setRightComponent(jScrollPane2);

        jEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        jSplitPane1.setTopComponent(jScrollPane1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void findAnnotation(){
        
    }

  
    private void jButtonAnalyzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnalyzeMouseClicked
        
            findAnnotation();
        
    }//GEN-LAST:event_jButtonAnalyzeMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalyze;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaInput;
    // End of variables declaration//GEN-END:variables

}
