/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CGRecognitionPanel.java
 *
 * Created on Sep 27, 2009, 7:47:07 PM
 */

package edu.tuke.beast.panel;

import edu.tuke.beast.Beast;
import edu.tuke.beast.cortex.ConceptCortex;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.beast.lexicon.Lexicon;
import edu.tuke.beast.token.Token;
import java.util.Vector;

/**
 *
 * @author blur
 */
public class CGRecognitionPanel extends BeastPanel {

    private static final long serialVersionUID = -7878987972121778152L;
    private ConceptCortex cc;


    /** Creates new form CGRecognitionPanel */
    public CGRecognitionPanel() {
        initComponents();
    }

    public CGRecognitionPanel(Beast b) {
        super(b);
        initComponents();
        cc = new ConceptCortex(cortex);
        setName("Conceptual Graph");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButtonRecoCG = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInput);

        jSplitPane1.setTopComponent(jScrollPane1);

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOutput);

        jSplitPane1.setRightComponent(jScrollPane2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButtonRecoCG.setText("Find CG");
        jButtonRecoCG.setDoubleBuffered(true);
        jButtonRecoCG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecoCGActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRecoCG, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRecoCGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecoCGActionPerformed
     logger.debug("reco button clicked");
     String inputString = jTextAreaInput.getText();

     Vector<Integer> input = new Vector<Integer> ();
     Lexicon<String> lex = beast.getLexicon();

     for(String word : inputString.split(" ")){
        Integer i = lex.getIndex(new Token<String>(word));
        input.add(i);
     }

     String output = cc.getSentence(input);

     jTextAreaOutput.setText(output);
    }//GEN-LAST:event_jButtonRecoCGActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonRecoCG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaInput;
    private javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables

}
