/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConceptPanel.java
 *
 * Created on Apr 13, 2009, 10:46:52 PM
 */
package edu.tuke.beast.panel;

import edu.tuke.visu.tablemodel.JCommonModel;
import edu.tuke.beast.Beast;
import edu.tuke.beast.cortex.ConceptCortex;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.beast.lexicon.Lexicon;
import edu.tuke.beast.token.Token;
import edu.tuke.visu.tablemodel.JCommonDefaultModel;
import java.util.Set;
import java.util.Vector;
import javax.swing.JTable;

/**
 *
 * @author vrockai
 */
public class ConceptPanel extends BeastPanel {

    private static final long serialVersionUID = -8600931409425010749L;
    
    ConceptCortex cc = null;

    /** Creates new form ConceptPanel */
    public ConceptPanel() {
        initComponents();
    }

    public ConceptPanel(Beast b) {
        super(b);
        this.beast = b;
        cc = new ConceptCortex(cortex);
        initComponents();
         setName("Concepts");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());

        jButton1.setText("Identify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jButton2.setText("set Treshold");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        Vector<String> columns = new Vector<String>();
        columns.add("#");
        columns.add("word");
        columns.add("strength");
        Class[] classes = {Integer.class, String.class, Double.class};

        Lexicon<String> l = beast.getLexicon();
        Set<Integer> sl = l.getHashMap().keySet();

        Integer a = l.getIndex(new Token<String>("henry"));
JCommonDefaultModel newTabMod = new JCommonDefaultModel(columns, classes);
        int c = 0;
        for (Integer j : l.getHashMap().keySet()) {
            for (Integer i : sl) {
                if (cc.isConcept(j, i)) {
                    Vector<Object> row = new Vector<Object>(3);
                    row.add(c++);
                    row.add(l.getEntry(j) + " " + l.getEntry(i));
                    row.add(cc.getConceptStrenght(j, i));
                    newTabMod.addRow(row);
                }
            }
        }

newTabMod.sort(2,false);

        jTable1 = new JTable(newTabMod);
        jTable1.setDefaultRenderer(Double.class, new JCommonModel.DoubleRenderer());
        jTable1.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jTable1);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double tres = Double.valueOf(jTextField1.getText());
        cc.setTreshold(tres);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
