/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CGRecognitionPanel.java
 *
 * Created on Sep 27, 2009, 7:47:07 PM
 */
package edu.tuke.beast.panel;

import edu.tuke.beast.Beast;
import edu.tuke.beast.cortex.ClusterCortex;
import edu.tuke.beast.cortex.ConceptCortex;
import edu.tuke.beast.cortex.Cortex;
import edu.tuke.beast.cortex.SimilarityCortex;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.beast.lexicon.Lexicon;
import edu.tuke.beast.token.Token;
import java.util.*;

/**
 *
 * @author blur
 */
public class ConcepClusterPanel extends BeastPanel {

    private static final long serialVersionUID = -7878987972124478152L;
    private ClusterCortex cc;

    /**
     * Creates new form CGRecognitionPanel
     */
    public ConcepClusterPanel() {
        initComponents();
    }

    public ConcepClusterPanel(Beast b) {
        super(b);
        initComponents();
        cc = new ClusterCortex(cortex);
        setName("Concept clustering");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        computeButton = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        input2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        input3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        computeButton.setText("Find cluster");
        computeButton.setDoubleBuffered(true);
        computeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(computeButton, java.awt.BorderLayout.CENTER);

        jLabel1.setText("eta");
        jPanel3.add(jLabel1);

        jTextField1.setText("1.0");
        jPanel3.add(jTextField1);

        jButton1.setText("Set eta"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("word 1:");
        jPanel2.add(jLabel2);

        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        input1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input1KeyReleased(evt);
            }
        });
        jPanel2.add(input1);
        jPanel2.add(jSeparator1);

        jLabel3.setText("word 2:");
        jPanel2.add(jLabel3);

        input2.setMinimumSize(new java.awt.Dimension(80, 19));
        input2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input2KeyReleased(evt);
            }
        });
        jPanel2.add(input2);

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jSeparator2);

        jLabel4.setText("word 3:");
        jPanel2.add(jLabel4);

        input3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input3KeyReleased(evt);
            }
        });
        jPanel2.add(input3);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeButtonActionPerformed
        logger.debug("find cluster button clicked");
        //double tresh = 1.5;

        Cortex cortex = beast.getCortex();
        Lexicon<String> lexicon = beast.getLexicon();

        Set<Set<Integer>> aset = new HashSet<Set<Integer>>();

        List<String> input = new ArrayList<String>();
        input.add(input1.getText());
        input.add(input2.getText());
        input.add(input3.getText());
        //Must be in lexicon

        Set<Integer> qset = new HashSet<Integer>();
        for (String day : input) {
            System.out.println(day);
            qset.add(lexicon.getIndex(day));
        }
        aset.add(qset);

        //cortex.setTreshold(tresh);
        cc.setTreshold(cortex.getTreshold());

        cc.setStrategy(SimilarityCortex.Strategy.INTERSECTION);
        Set<Integer> lset = lexicon.getLexiconSet();

        StringBuffer sb = new StringBuffer();
        for (Set<Integer> qqset : aset) {

            Set<Integer> result = cc.getCluster(qqset, lset, false);

            for (Integer i : result) {
                sb.append(lexicon.getEntry(i).getValue() + ", ");
            }
            sb.append("size: " + result.size());
        }

        jTextArea1.setText(sb.toString());

    }//GEN-LAST:event_computeButtonActionPerformed

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input1ActionPerformed

    private void input1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input1KeyReleased
        setValidationColor(input1);
        // TODO add your handling code here:
    }//GEN-LAST:event_input1KeyReleased

    private void input2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input2KeyReleased
        setValidationColor(input2);        // TODO add your handling code here:
    }//GEN-LAST:event_input2KeyReleased

    private void input3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input3KeyReleased
        setValidationColor(input3);        // TODO add your handling code here:
    }//GEN-LAST:event_input3KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double eta = Double.valueOf(jTextField1.getText());
        cc.setEta(eta);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton computeButton;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
