/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContextPanel.java
 *
 * Created on Dec 28, 2008, 6:30:32 PM
 */
package edu.tuke.beast.panel;

import edu.tuke.visu.tablemodel.JCommonModel;
import edu.tuke.beast.Beast;
import edu.tuke.beast.cortex.ContextCortex;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.beast.lexicon.Lexicon;
import edu.tuke.beast.token.Token;
import edu.tuke.visu.tablemodel.JCommonDefaultModel;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;

/**
 *
 * @author vrockai
 */
public class ContextPanel extends BeastPanel {

    private static final long serialVersionUID = -6142335308129768611L;
    private ContextCortex.Strategy contextStr = ContextCortex.Strategy.SUM;

    /** Creates new form ContextPanel */
    public ContextPanel() {
        initComponents();
    }

    public ContextPanel(Beast b) {
        super(b);
        this.beast = b;
        initComponents();
        setName("Context");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContext = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);

        jComboBox1.setModel(new DefaultComboBoxModel(ContextCortex.Strategy.values()));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/tango/16x16/actions/system-search.png"))); // NOI18N
        jButton1.setText("Find context");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTableContext.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableContext);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void computeContext(){
        Lexicon<String> l = beast.getLexicon();
        String[] words = jTextField2.getText().split(",");

        Vector<Map<Integer, Double>> sets = new Vector<Map<Integer, Double>>();

        for (String word : words) {
            word = word.trim();
            sets.add(countConsensus(l.getIndex(new Token<String>(word))));
        }


        Map<Integer, Double> result = cortex.maxMin(sets);

        logger.debug("result size: " + result.size());
        int c = 0;

        Vector<String> columns = new Vector<String>();
        columns.add("#");
        columns.add("word");
        columns.add("strength");
        Class[] classes = {Integer.class, String.class, Double.class};

        JCommonDefaultModel newTabMod = new JCommonDefaultModel(columns, classes);

        for (Map.Entry<Integer, Double> ei : result.entrySet()) {
            String token = l.getEntry(ei.getKey()).getValue();
            Vector<Object> row = new Vector<Object>();
            row.add(c++);
            row.add(token);
            row.add(ei.getValue());
            newTabMod.addRow(row);
        }

        newTabMod.sort(2,false);
        jTableContext = new JTable(newTabMod);
        jTableContext.setDefaultRenderer(Double.class, new JCommonModel.DoubleRenderer());
        jTableContext.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jTableContext);
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        computeContext();        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String conStr = jComboBox1.getSelectedItem().toString();
        logger.debug("C-STR: " + jComboBox1.getSelectedItem());
        contextStr = ContextCortex.Strategy.valueOf(conStr);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        computeContext();
    }//GEN-LAST:event_jButton1ActionPerformed

    private Map<Integer, Double> countConsensus(int t) {
        ContextCortex cc = new ContextCortex(cortex);
        Lexicon<String> l = beast.getLexicon();
        Vector<Integer> vt = new Vector<Integer>(1);
        vt.add(t);
        return cc.getRelatives(vt, l.getHashMap().keySet(), contextStr);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContext;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
