/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhrasePanel.java
 *
 * Created on Dec 8, 2008, 7:15:32 PM
 */
package edu.tuke.beast.panel;

import edu.tuke.beast.Beast;
import edu.tuke.beast.association.NewAssociation;
import edu.tuke.beast.cortex.ContentCortex;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.beast.token.Token;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author blur
 */
public class ContentSimilarityPanel extends BeastPanel {

    private static final long serialVersionUID = -3196363434750947467L;
    
    ContentCortex cc;
    public static final Token NULL_TOKEN = new Token<String>(null);

    /** Creates new form PhrasePanel */
    public ContentSimilarityPanel() {
        initComponents();
    }

    public ContentSimilarityPanel(Beast b) {
        super(b);
        initComponents();
        beast = b;
        cc = new ContentCortex(cortex);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    /*
    I'm writing this in English because I want as many people as possible to be able to read this. This is to show how a simple gesture can make someone's day and how if everyone were like this the world could be a much better place. This is also my way to say thank you to a stranger that was incredibly kind hearted. Picture the scene. As I step out of a restaurant from lunch, 13 blocks away from the office, it is raining and I have no umbrella. I decide to walk towards the subway, which was closer than walking all the way back to the office, but wasn't near either. As I stop at a traffic light, waiting to cross, with raining pouring over me, a stranger covers me with his umbrella. As the light turns green and we start to cross, he looks at me, and tells me that he his getting in the building in front of us and tells me to keep his umbrella. I said I could not and he insisted. I took his umbrella and kept a smile on my face all the way back to the office.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("M1:");
        jPanel2.add(jLabel1);

        jProgressBar2.setToolTipText("0%");
        jProgressBar2.setStringPainted(true);
        jPanel2.add(jProgressBar2);

        jLabel3.setText("M2:");
        jPanel2.add(jLabel3);

        jProgressBar1.setStringPainted(true);
        jPanel2.add(jProgressBar1);

        jPanel1.add(jPanel2);

        jButton1.setText("analyze");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jSplitPane1.setBottomComponent(jScrollPane2);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jSplitPane1.setLeftComponent(jScrollPane3);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void compareDocuments() throws IOException {
        String input_str1 = jTextArea1.getText();
        String input_str2 = jTextArea2.getText();

        List<Integer> input1 = beast.getLexicon().lexiconize(input_str1);
        List<Integer> input2 = beast.getLexicon().lexiconize(input_str2);

        Map<NewAssociation, Integer> m1 = cc.getAssociations(input1);
        Map<NewAssociation, Integer> m2 = cc.getAssociations(input2);

        double asSimi = cc.getAssociationSimilarity(m1, m2);

        jLabel1.setText(String.valueOf(asSimi));
        jProgressBar1.setValue((int) (asSimi * 100));
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {

            compareDocuments();
        } catch (IOException ex) {
            Logger.getLogger(ContentSimilarityPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    /*
    public static void main(String s[]) {

    Cortex cortex = null;
    try {
    cortex = new Cortex("/home/blur/Projects/Beast/CORTEX");
    } catch (Exception ex) {
    Logger.getLogger(BeastGui.class.getName()).log(Level.SEVERE, null, ex);
    }

    JFrame f = new JFrame("ContentPanel");
    f.addWindowListener(new WindowAdapter() {

    public void windowClosing(WindowEvent e) {
    System.exit(0);
    }
    });
    JPanel applet = new ContentSimilarityPanel(cortex);

    f.getContentPane().add("Center", applet);

    f.pack();

    f.setVisible(true);
    }
     * */
}
