/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnalyzePanel.java
 *
 * Created on Dec 7, 2008, 3:31:31 AM
 */
package edu.tuke.beast.panel;

import edu.tuke.beast.Beast;
import edu.tuke.beast.gui.BeastPanel;
import edu.tuke.visu.canvas.WordcircleCanvas;
import edu.tuke.beast.token.ExcitedIndex;
import edu.tuke.beast.token.Token;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author blur
 */
public class IdentificationPanel extends BeastPanel {

    private static final long serialVersionUID = 2527492140764775480L;
    final WordcircleCanvas sPanel = new WordcircleCanvas();

    /** Creates new form AnalyzePanel */
    public IdentificationPanel() {
        initComponents();
    }

    public IdentificationPanel(Beast b) {
        initComponents();
        this.beast = b;
        this.add(sPanel, BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextField.setText("text to analyze...");
        jTextField.addKeyListener(new java.awt.event.KeyAdapter() {

            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField, java.awt.BorderLayout.CENTER);

        jButton.setText("OK");
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jButton, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>

    private void jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendText();
        }
    }

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {

        sendText();
    }

    private void sendText() {
        String input = jTextField.getText();
        String text[] = input.split(" ");

        List<ExcitedIndex<String>> words = new ArrayList<ExcitedIndex<String>>();
        double sig_m[][] = new double[text.length][text.length];
        double wei_m[][] = new double[text.length][text.length];

        for (String word : text) {
            int occ = beast.getLexicon().getOccurences(new Token<String>(word));
            System.out.println(word + ':' + occ);
            words.add(new ExcitedIndex<String>(word, occ));
        }

        for (int i = 0; i < text.length - 1; i++) {
            for (int j = i + 1; j < text.length; j++) {
                int a = beast.getLexicon().getIndex(new Token<String>(text[i]));
                int b = beast.getLexicon().getIndex(new Token<String>(text[j]));
                if (j - i - 1 < beast.getRegion().fascicle.length) {
                    double sig = beast.getRegion().getFascicle(j - i - 1).getSignificance(a, b);
                    double wei = beast.getRegion().getFascicle(j - i - 1).getWeigth(a, b);
                    System.out.println(text[i] + "->" + text[j] + '=' + ((Math.floor(sig * 10000)) / 10000) + ':' + ((Math.floor(wei * 10000)) / 10000));

                    sig_m[i][j] = (Math.floor(sig * 10000)) / 10000;
                    wei_m[i][j] = (Math.floor(wei * 10000)) / 10000;
                }

            }
        }

        sPanel.setSentence(words, sig_m, wei_m);
    //sPanel.repaint();
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField;
    // End of variables declaration
}
