/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SplashPanel.java
 *
 * Created on Apr 14, 2009, 3:52:10 PM
 */
package edu.tuke.beast.panel;

/**
 *
 * @author vrockai
 */
public class SplashPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 8092976078146593247L;

    /** Creates new form SplashPanel */
    public SplashPanel() {
        initComponents();
        
    }

    public void setStatus(int i) {
        if (i > 100) {
            i = 100;
        }
        if (i < 0) {
            i = 0;
        }
        jProgressBar.setValue(i);
        jProgressBar.setString(i + "%");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new java.awt.BorderLayout());

        jProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar.setBorder(null);
        jProgressBar.setStringPainted(true);
        add(jProgressBar, java.awt.BorderLayout.SOUTH);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/tuke/beast/img/kingkong.jpg"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
