import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on March 13, 2007, 11:29 PM
 */

/**
 *
 * @author blur
 */
public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(edu.tuke.beast.BeastSuite.suite());
        suite.addTest(edu.tuke.beast.association.AssociationSuite.suite());
        suite.addTest(edu.tuke.beast.fascicle.FascicleSuite.suite());
        suite.addTest(edu.tuke.beast.input.InputSuite.suite());
        suite.addTest(edu.tuke.beast.lexicon.LexiconSuite.suite());
        suite.addTest(edu.tuke.beast.token.TokenSuite.suite());
        return suite;
    }
    
}
