/*
 * LexiconSuite.java
 * JUnit based test
 *
 * Created on March 13, 2007, 11:29 PM
 */

package edu.tuke.beast.lexicon;

import junit.framework.*;

/**
 *
 * @author blur
 */
public class LexiconSuite extends TestCase {
    
    public LexiconSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("LexiconSuite");
        suite.addTest(edu.tuke.beast.lexicon.LexiconTest.suite());
        suite.addTest(edu.tuke.beast.lexicon.LexiconTest.suite());
        return suite;
    }
    
}
