/*
 * BeastSuite.java
 * JUnit based test
 *
 * Created on March 13, 2007, 11:29 PM
 */

package edu.tuke.beast;

import junit.framework.*;

/**
 *
 * @author blur
 */
public class BeastSuite extends TestCase {
    
    public BeastSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("BeastSuite");
        suite.addTest(edu.tuke.beast.cortex.CortexTest.suite());
        suite.addTest(edu.tuke.beast.RegionTest.suite());
        return suite;
    }
    
}
