/*
 * AssociationSuite.java
 * JUnit based test
 *
 * Created on March 13, 2007, 11:29 PM
 */

package edu.tuke.beast.association;

import junit.framework.*;

/**
 *
 * @author blur
 */
public class AssociationSuite extends TestCase {
    
    public AssociationSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("AssociationSuite");
        suite.addTest(edu.tuke.beast.association.AssociationTest.suite());
        return suite;
    }
    
}
